# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='abbreviation',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='full_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='short_name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
