# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
        ('teams', '0002_auto_20180821_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='countries.Country'),
            preserve_default=False,
        ),
    ]
