# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_auto_20180823_1116'),
        ('teams', '0003_club_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='current_league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='games.League'),
            preserve_default=False,
        ),
    ]
