# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
        ('games', '0003_auto_20180821_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('abbreviation', models.CharField(max_length=3)),
                ('tier', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='countries.Country')),
            ],
        ),
        migrations.RemoveField(
            model_name='competition',
            name='country',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='tier',
        ),
        migrations.AddField(
            model_name='competition',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='games.Season'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='years', to='games.League'),
            preserve_default=False,
        ),
    ]
