# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
        ('teams', '0003_club_country'),
        ('games', '0004_auto_20180821_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='countries.Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='teams', to='teams.Team'),
        ),
    ]
