# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20180821_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='games.League'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='games.Competition'),
        ),
    ]
