# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20180821_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='league',
        ),
        migrations.RemoveField(
            model_name='game',
            name='season',
        ),
    ]
