# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20180822_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='tie_breaker_2',
            field=models.CharField(blank=True, choices=[('Goal Average', 'Goal Average'), ('Goal Difference', 'Goal Difference'), ('Goals Scored', 'Goals Scored'), ('Games Won', 'Games Won')], max_length=25, null=True),
        ),
    ]
