# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_auto_20180822_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='away_draw_points',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='competition',
            name='away_loss_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competition',
            name='away_win_points',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='competition',
            name='home_draw_points',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='competition',
            name='home_loss_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competition',
            name='home_win_points',
            field=models.IntegerField(default=3),
        ),
    ]
