# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_auto_20180822_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='tie_breaker_1',
            field=models.CharField(choices=[('Goal Average', 'Goal Average'), ('Goal Difference', 'Goal Difference'), ('Goals Scored', 'Goals Scored'), ('Games Won', 'Games Won'), ('Name', 'Name')], default='Name', max_length=25),
        ),
        migrations.AlterField(
            model_name='competition',
            name='tie_breaker_2',
            field=models.CharField(choices=[('Goal Average', 'Goal Average'), ('Goal Difference', 'Goal Difference'), ('Goals Scored', 'Goals Scored'), ('Games Won', 'Games Won'), ('Name', 'Name')], default='Name', max_length=25),
        ),
        migrations.AlterField(
            model_name='competition',
            name='tie_breaker_3',
            field=models.CharField(choices=[('Goal Average', 'Goal Average'), ('Goal Difference', 'Goal Difference'), ('Goals Scored', 'Goals Scored'), ('Games Won', 'Games Won'), ('Name', 'Name')], default='Name', max_length=25),
        ),
        migrations.AlterField(
            model_name='competition',
            name='tie_breaker_4',
            field=models.CharField(choices=[('Goal Average', 'Goal Average'), ('Goal Difference', 'Goal Difference'), ('Goals Scored', 'Goals Scored'), ('Games Won', 'Games Won'), ('Name', 'Name')], default='Name', max_length=25),
        ),
        migrations.AlterField(
            model_name='competition',
            name='tie_breaker_5',
            field=models.CharField(choices=[('Goal Average', 'Goal Average'), ('Goal Difference', 'Goal Difference'), ('Goals Scored', 'Goals Scored'), ('Games Won', 'Games Won'), ('Name', 'Name')], default='Name', max_length=25),
        ),
    ]
