# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_club_country'),
        ('games', '0012_auto_20180822_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='games.Competition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='teams.Team')),
            ],
        ),
    ]
