# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_auto_20180823_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='games.Season'),
            preserve_default=False,
        ),
    ]
