# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0021_competition_subsidiaries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='subsidiaries',
        ),
        migrations.AddField(
            model_name='competition',
            name='subsidiaries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.Competition'),
        ),
    ]
