# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0022_auto_20180903_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='subsidiaries',
        ),
        migrations.AddField(
            model_name='competition',
            name='subsidiaries',
            field=models.ManyToManyField(blank=True, to='games.Competition'),
        ),
    ]
