# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-04 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0023_auto_20180903_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='neutral_venue',
            field=models.BooleanField(default=False),
        ),
    ]
